steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
   'build',
   '-t', 'gcr.io/$PROJECT_ID/gojek:compute-$SHORT_SHA',
   '-t', 'gcr.io/$PROJECT_ID/gojek:compute',
   '.', '-f', 'Dockerfile.compute'
  ]
  dir: 'precompute'
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--build-arg', 'APPDIR=geoapi',
    '-t', 'gcr.io/$PROJECT_ID/gojek:geoapi-$SHORT_SHA',
    '-t', 'gcr.io/$PROJECT_ID/gojek:geoapi',
    '.', '-f', 'Dockerfile.geoapi'
    ]
  dir: 'components'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - gojek-microservice-geoapi
  - geoapi=gcr.io/$PROJECT_ID/gojek:geoapi-$SHORT_SHA
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=altimit'
images:
  - 'gcr.io/$PROJECT_ID/gojek:geoapi-$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/gojek:geoapi'
  - 'gcr.io/$PROJECT_ID/gojek:compute-$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/gojek:compute'
