from etheleon/docker-alpine-python-machinelearning
LABEL maintainer=etheleon@protonmail.com

ARG APPDIR

COPY ${APPDIR} /geoapi

WORKDIR /geoapi

RUN pip install --no-cache-dir -r requirements/all.txt

CMD ["gunicorn", "-b", "0.0.0.0:5001", "--log-level", "info", "--pythonpath=/geoapi/app", "--timeout=120", "app:create_app()"]
